/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokergame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;
/**
 *
 * @author SHER
 */
public class PokerMatch extends javax.swing.JFrame {
public PokerMain pokermain;
public HttpWrapper http;

    /**
     * Creates new form PokerTable2
     */
    public PokerMatch() {
  initComponents();
  hide_unwanted_elements();
    
        betting_panel.setVisible(false);
            pokermain=new PokerMain(); 
        http=new HttpWrapper();
         join_to_room();
         pokermain.get_players(this);
    }
    
    public void hide_unwanted_elements(){
        player6_chips.setVisible(false);      
        player1_chips.setVisible(false);
        player2_chips.setVisible(false);
        player3_chips.setVisible(false);
        player4_chips.setVisible(false);
        player5_chips.setVisible(false);
        player5_bet_status.setVisible(false);
        player6_bet_status1.setVisible(false);
        player2_bet_status1.setVisible(false);
        player1_bet_status1.setVisible(false);
        player3_bet_status1.setVisible(false);
        player4_bet_status1.setVisible(false);
    }
public void join_to_room(){
 

          String result;
        try {
            result = http.getRemoteContents(http.connecturl);
            JsonWrapper json=new JsonWrapper(result);
            pokermain.room_id=json.get_int("room_id");
            pokermain.my_playerid=json.get_int("player_id");
         //      JOptionPane.showMessageDialog(null,"Connected to a Game Room");
        } catch (Exception ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }   
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  

    } 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player4_label = new javax.swing.JLabel();
        player3_label = new javax.swing.JLabel();
        player2_label = new javax.swing.JLabel();
        player1_label = new javax.swing.JLabel();
        player6_label = new javax.swing.JLabel();
        player5_label = new javax.swing.JLabel();
        middle_card1 = new javax.swing.JLabel();
        middle_card2 = new javax.swing.JLabel();
        middle_card3 = new javax.swing.JLabel();
        middle_card4 = new javax.swing.JLabel();
        middle_card5 = new javax.swing.JLabel();
        main_label_center = new javax.swing.JLabel();
        player_id = new javax.swing.JLabel();
        mycard1 = new javax.swing.JLabel();
        mycard2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        player_4_updates = new javax.swing.JLabel();
        betting_panel = new javax.swing.JPanel();
        btn_fold = new javax.swing.JButton();
        btn_check = new javax.swing.JButton();
        btn_call = new javax.swing.JButton();
        raise_slider = new javax.swing.JSlider();
        btn_raise = new javax.swing.JButton();
        raise_amount = new javax.swing.JLabel();
        game_id_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        player6_balance = new javax.swing.JLabel();
        player1_balance = new javax.swing.JLabel();
        player2_balance = new javax.swing.JLabel();
        player3_balance = new javax.swing.JLabel();
        player4_balance = new javax.swing.JLabel();
        player6_chips = new javax.swing.JLabel();
        player5_balance = new javax.swing.JLabel();
        player1_chips = new javax.swing.JLabel();
        player2_chips = new javax.swing.JLabel();
        player3_chips = new javax.swing.JLabel();
        player4_chips = new javax.swing.JLabel();
        player5_chips = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        player5_bet_status = new javax.swing.JLabel();
        player6_bet_status1 = new javax.swing.JLabel();
        player2_bet_status1 = new javax.swing.JLabel();
        player1_bet_status1 = new javax.swing.JLabel();
        player3_bet_status1 = new javax.swing.JLabel();
        player4_bet_status1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        total_chip_count = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(986, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        player4_label.setText("You");
        getContentPane().add(player4_label);
        player4_label.setBounds(490, 530, 110, 14);

        player3_label.setText("Player 3 Loading");
        getContentPane().add(player3_label);
        player3_label.setBounds(830, 340, 180, 14);

        player2_label.setText("Plyaer 2 Loading");
        getContentPane().add(player2_label);
        player2_label.setBounds(820, 130, 150, 14);

        player1_label.setText("Player 1 Loading");
        getContentPane().add(player1_label);
        player1_label.setBounds(460, 80, 140, 14);

        player6_label.setBackground(new java.awt.Color(0, 0, 0));
        player6_label.setText("Player 7 Loading");
        getContentPane().add(player6_label);
        player6_label.setBounds(90, 130, 140, 14);

        player5_label.setText("Player 5 Loading");
        getContentPane().add(player5_label);
        player5_label.setBounds(100, 340, 140, 10);

        middle_card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        getContentPane().add(middle_card1);
        middle_card1.setBounds(320, 240, 70, 90);

        middle_card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        middle_card2.setText("2");
        getContentPane().add(middle_card2);
        middle_card2.setBounds(400, 240, 70, 90);

        middle_card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        getContentPane().add(middle_card3);
        middle_card3.setBounds(480, 240, 70, 90);

        middle_card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        middle_card4.setText("4");
        getContentPane().add(middle_card4);
        middle_card4.setBounds(560, 240, 70, 90);

        middle_card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        getContentPane().add(middle_card5);
        middle_card5.setBounds(640, 240, 70, 90);

        main_label_center.setText("Game Hasnt Started Yet");
        getContentPane().add(main_label_center);
        main_label_center.setBounds(460, 204, 170, 20);

        player_id.setText("jLabel1");
        getContentPane().add(player_id);
        player_id.setBounds(380, 160, 34, 14);

        mycard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        getContentPane().add(mycard1);
        mycard1.setBounds(420, 440, 70, 90);

        mycard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        getContentPane().add(mycard2);
        mycard2.setBounds(500, 440, 70, 90);

        jPanel9.setOpaque(false);
        jPanel9.add(player_4_updates);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(480, 450, 10, 10);

        betting_panel.setBackground(new java.awt.Color(255, 51, 153));
        betting_panel.setOpaque(false);

        btn_fold.setText("Fold");
        btn_fold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_foldActionPerformed(evt);
            }
        });
        betting_panel.add(btn_fold);

        btn_check.setText("Check");
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        betting_panel.add(btn_check);

        btn_call.setText("Call");
        btn_call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_callActionPerformed(evt);
            }
        });
        betting_panel.add(btn_call);

        raise_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                raise_sliderStateChanged(evt);
            }
        });
        betting_panel.add(raise_slider);

        btn_raise.setText("Raise");
        btn_raise.setToolTipText("");
        btn_raise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raiseActionPerformed(evt);
            }
        });
        betting_panel.add(btn_raise);
        betting_panel.add(raise_amount);

        getContentPane().add(betting_panel);
        betting_panel.setBounds(0, 570, 980, 36);

        game_id_lbl.setText("jLabel1");
        getContentPane().add(game_id_lbl);
        game_id_lbl.setBounds(610, 160, 34, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 190, 70, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 400, 70, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 70, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(890, 400, 70, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel6.setText("jLabel2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 400, 70, 90);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel7.setText("jLabel2");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(900, 190, 70, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel8.setText("jLabel2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(820, 400, 70, 90);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel10.setText("jLabel2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 30, 70, 90);
        getContentPane().add(player6_balance);
        player6_balance.setBounds(90, 150, 0, 0);
        getContentPane().add(player1_balance);
        player1_balance.setBounds(480, 100, 0, 0);
        getContentPane().add(player2_balance);
        player2_balance.setBounds(840, 150, 0, 0);

        player3_balance.setText("jLabel9");
        getContentPane().add(player3_balance);
        player3_balance.setBounds(850, 360, 34, 14);
        getContentPane().add(player4_balance);
        player4_balance.setBounds(600, 470, 0, 0);

        player6_chips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/rsz_poker-chips.png"))); // NOI18N
        getContentPane().add(player6_chips);
        player6_chips.setBounds(200, 80, 130, 40);
        getContentPane().add(player5_balance);
        player5_balance.setBounds(120, 360, 0, 0);

        player1_chips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/rsz_poker-chips.png"))); // NOI18N
        getContentPane().add(player1_chips);
        player1_chips.setBounds(590, 80, 130, 30);

        player2_chips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/rsz_poker-chips.png"))); // NOI18N
        getContentPane().add(player2_chips);
        player2_chips.setBounds(840, 290, 110, 30);

        player3_chips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/rsz_poker-chips.png"))); // NOI18N
        player3_chips.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(player3_chips);
        player3_chips.setBounds(730, 420, 120, 30);

        player4_chips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/rsz_poker-chips.png"))); // NOI18N
        player4_chips.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(player4_chips);
        player4_chips.setBounds(330, 440, 100, 30);

        player5_chips.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/rsz_poker-chips.png"))); // NOI18N
        getContentPane().add(player5_chips);
        player5_chips.setBounds(180, 410, 80, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel11.setText("jLabel2");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 30, 70, 90);

        player5_bet_status.setBackground(new java.awt.Color(0, 102, 51));
        player5_bet_status.setForeground(new java.awt.Color(255, 255, 255));
        player5_bet_status.setText("        jLabel9");
        player5_bet_status.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        player5_bet_status.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player5_bet_status.setOpaque(true);
        getContentPane().add(player5_bet_status);
        player5_bet_status.setBounds(70, 290, 90, 30);

        player6_bet_status1.setBackground(new java.awt.Color(0, 102, 51));
        player6_bet_status1.setForeground(new java.awt.Color(255, 255, 255));
        player6_bet_status1.setText("        jLabel9");
        player6_bet_status1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        player6_bet_status1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player6_bet_status1.setOpaque(true);
        getContentPane().add(player6_bet_status1);
        player6_bet_status1.setBounds(90, 80, 90, 30);

        player2_bet_status1.setBackground(new java.awt.Color(0, 102, 51));
        player2_bet_status1.setForeground(new java.awt.Color(255, 255, 255));
        player2_bet_status1.setText("        jLabel9");
        player2_bet_status1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        player2_bet_status1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player2_bet_status1.setOpaque(true);
        getContentPane().add(player2_bet_status1);
        player2_bet_status1.setBounds(830, 80, 90, 30);

        player1_bet_status1.setBackground(new java.awt.Color(0, 102, 51));
        player1_bet_status1.setForeground(new java.awt.Color(255, 255, 255));
        player1_bet_status1.setText("        jLabel9");
        player1_bet_status1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        player1_bet_status1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player1_bet_status1.setOpaque(true);
        getContentPane().add(player1_bet_status1);
        player1_bet_status1.setBounds(460, 30, 90, 30);

        player3_bet_status1.setBackground(new java.awt.Color(0, 102, 51));
        player3_bet_status1.setForeground(new java.awt.Color(255, 255, 255));
        player3_bet_status1.setText("        jLabel9");
        player3_bet_status1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        player3_bet_status1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player3_bet_status1.setOpaque(true);
        getContentPane().add(player3_bet_status1);
        player3_bet_status1.setBounds(850, 500, 90, 30);

        player4_bet_status1.setBackground(new java.awt.Color(0, 102, 51));
        player4_bet_status1.setForeground(new java.awt.Color(255, 255, 255));
        player4_bet_status1.setText("        jLabel9");
        player4_bet_status1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        player4_bet_status1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player4_bet_status1.setOpaque(true);
        getContentPane().add(player4_bet_status1);
        player4_bet_status1.setBounds(580, 440, 90, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/FOK.jpg"))); // NOI18N
        jLabel12.setText("jLabel2");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(830, 190, 70, 90);

        total_chip_count.setText("$0");
        total_chip_count.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(total_chip_count);
        total_chip_count.setBounds(460, 370, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokergame/poker_images/new_table.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 986, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raise_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_raise_sliderStateChanged
        raise_amount.setText(String.valueOf(raise_slider.getValue()));
    }//GEN-LAST:event_raise_sliderStateChanged

    private void btn_raiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raiseActionPerformed
        pokermain.place_bet(this,"raise");
    }//GEN-LAST:event_btn_raiseActionPerformed

    private void btn_callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_callActionPerformed
        pokermain.place_bet(this,"call");
    }//GEN-LAST:event_btn_callActionPerformed

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        pokermain.place_bet(this,"check");
    }//GEN-LAST:event_btn_checkActionPerformed

    private void btn_foldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_foldActionPerformed
        pokermain.place_bet(this,"fold");
    }//GEN-LAST:event_btn_foldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokerMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokerMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokerMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokerMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokerMatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel betting_panel;
    public javax.swing.JButton btn_call;
    public javax.swing.JButton btn_check;
    public javax.swing.JButton btn_fold;
    public javax.swing.JButton btn_raise;
    public javax.swing.JLabel game_id_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel main_label_center;
    public javax.swing.JLabel middle_card1;
    public javax.swing.JLabel middle_card2;
    public javax.swing.JLabel middle_card3;
    public javax.swing.JLabel middle_card4;
    public javax.swing.JLabel middle_card5;
    public javax.swing.JLabel mycard1;
    public javax.swing.JLabel mycard2;
    public javax.swing.JLabel player1_balance;
    public javax.swing.JLabel player1_bet_status1;
    public javax.swing.JLabel player1_chips;
    public javax.swing.JLabel player1_label;
    public javax.swing.JLabel player2_balance;
    public javax.swing.JLabel player2_bet_status1;
    public javax.swing.JLabel player2_chips;
    public javax.swing.JLabel player2_label;
    public javax.swing.JLabel player3_balance;
    public javax.swing.JLabel player3_bet_status1;
    public javax.swing.JLabel player3_chips;
    public javax.swing.JLabel player3_label;
    public javax.swing.JLabel player4_balance;
    public javax.swing.JLabel player4_bet_status1;
    public javax.swing.JLabel player4_chips;
    public javax.swing.JLabel player4_label;
    public javax.swing.JLabel player5_balance;
    public javax.swing.JLabel player5_bet_status;
    public javax.swing.JLabel player5_chips;
    public javax.swing.JLabel player5_label;
    public javax.swing.JLabel player6_balance;
    public javax.swing.JLabel player6_bet_status1;
    public javax.swing.JLabel player6_chips;
    public javax.swing.JLabel player6_label;
    public javax.swing.JLabel player_4_updates;
    public javax.swing.JLabel player_id;
    public javax.swing.JLabel raise_amount;
    public javax.swing.JSlider raise_slider;
    public javax.swing.JLabel total_chip_count;
    // End of variables declaration//GEN-END:variables
}
